### ISSUE TITLE
Linked chatbot repository not available

### ISSUE THREAD

**Issue by promasu** [dreamside-digital/safesupport-chatbox#3]
Hi there.
I wanted to setup the chatbox and chatbot but the linked Repository (https://github.com/nomadic-labs/safesupport-bot) is not available. Is there a way to get the bot from somewhere?

Thanks!

**Comment by s-kennedy** [comment]
Hi, I'm still working on updating the docs but it will be up soon.

**Comment by promasu** [comment]
Thank you
